version: '3.8'
services:
  slides-mcp:
    build: .
    container_name: slides-mcp
    working_dir: /app
    volumes:
      - /home/debian/mcpslide/botrun-google-slides-mcp/keys:/app/keys:ro
    command: ["node", "server-http.js"]
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "9002:9002"
